export async function onRequestGet() {
  return new Response(`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow">
<title>Parts Import Picking | DooPixel</title>
<style>
*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#181818}.wrap{max-width:1200px;margin:auto;padding:28px 18px 60px}header,.login,.tools,.head{display:flex;align-items:center;gap:10px}header,.head{justify-content:space-between}nav a{margin-right:12px;color:#111}input,select,button{min-height:42px;border:1px solid #bbb;padding:8px 11px;font:inherit}button{cursor:pointer;font-weight:700}.primary{background:#111;color:#fff}.tools{margin:22px 0;flex-wrap:wrap}.tools input{min-width:280px}.card{border:1px solid #ccc;padding:18px;margin:14px 0}.meta{color:#666;font-size:13px}.stats{margin:9px 0}table{width:100%;border-collapse:collapse;margin-top:14px}th,td{text-align:left;padding:8px;border-bottom:1px solid #ddd}th:last-child,td:last-child{text-align:right}.hidden{display:none}.notice{background:#f6f6f6;padding:14px;margin-top:16px}@media(max-width:650px){header,.head{display:block}.login{margin-top:14px;flex-wrap:wrap}.tools input{width:100%;min-width:0}.table{overflow:auto}}
</style></head><body><main class="wrap">
<header><div><h1>Parts Import Picking</h1><nav><a href="/admin/verified">Verified Designs</a><a href="/admin/review">Artwork Review</a><a href="/admin/comments">Comments</a><a href="/admin/parts-imports">Parts Picking</a></nav></div>
<form id="login" class="login"><input id="token" type="password" placeholder="Admin password"><button class="primary">Open</button></form></header>
<section id="area" class="hidden"><div class="tools"><select id="status"><option value="ordered">Ordered</option><option value="pending_order">Awaiting Checkout</option><option value="all">All</option></select><input id="search" type="search" placeholder="Search import ID, order or filename"><button id="refresh">Refresh</button></div><div id="list"></div><div id="empty" class="notice hidden">No matching parts imports.</div></section>
<div id="message" class="notice hidden"></div></main>
<script>
const tokenInput=document.getElementById('token'),area=document.getElementById('area'),list=document.getElementById('list'),message=document.getElementById('message'),empty=document.getElementById('empty');let token=sessionStorage.getItem('doopixelGalleryAdminToken')||'';
function msg(text){message.textContent=text;message.classList.toggle('hidden',!text)}
async function load(){msg('Loading...');const q='?status='+encodeURIComponent(document.getElementById('status').value)+'&q='+encodeURIComponent(document.getElementById('search').value.trim());const response=await fetch('/api/admin/parts-imports'+q,{headers:{authorization:'Bearer '+token}});const data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||'Request failed.');list.innerHTML='';data.imports.forEach(render);empty.classList.toggle('hidden',data.imports.length!==0);area.classList.remove('hidden');msg('')}
function render(item){const card=document.createElement('article');card.className='card';const head=document.createElement('div');head.className='head';const title=document.createElement('h2');title.textContent=(item.orderNumber?'Order #'+item.orderNumber+' · ':'')+item.id;const meta=document.createElement('span');meta.className='meta';meta.textContent=item.status==='ordered'?'ORDERED':'AWAITING CHECKOUT';head.append(title,meta);card.append(head);const stats=document.createElement('p');stats.className='stats';stats.textContent=item.totalPieces.toLocaleString()+' pieces · '+item.chargeBlocks+' packs · $'+(item.priceCents/100).toFixed(2)+' · '+item.colorLines+' pick lines';card.append(stats);const detail=document.createElement('p');detail.className='meta';detail.textContent='98138: '+item.flatPieces.toLocaleString()+' · 4073: '+item.raisedPieces.toLocaleString()+' · Ignored XML rows: '+item.ignoredLines+' · '+new Date(item.orderedAt||item.createdAt).toLocaleString();card.append(detail);const wrap=document.createElement('div');wrap.className='table';const table=document.createElement('table');table.innerHTML='<thead><tr><th>Warehouse No.</th><th>SKU</th><th>Part</th><th>Color / BrickLink ID</th><th>Pick Qty</th></tr></thead>';const body=document.createElement('tbody');item.lines.forEach(line=>{const tr=document.createElement('tr');[line.warehouseCode,line.sku,line.pieceType,line.colorName+' / '+line.bricklinkColorId,line.quantity.toLocaleString()].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td)});body.append(tr)});table.append(body);wrap.append(table);card.append(wrap);list.append(card)}
document.getElementById('login').addEventListener('submit',event=>{event.preventDefault();token=tokenInput.value.trim();sessionStorage.setItem('doopixelGalleryAdminToken',token);load().catch(error=>msg(error.message))});document.getElementById('refresh').addEventListener('click',()=>load().catch(error=>msg(error.message)));document.getElementById('status').addEventListener('change',()=>load().catch(error=>msg(error.message)));document.getElementById('search').addEventListener('input',()=>{clearTimeout(window.dpSearch);window.dpSearch=setTimeout(()=>load().catch(error=>msg(error.message)),300)});if(token)load().catch(()=>{token='';sessionStorage.removeItem('doopixelGalleryAdminToken')});
</script></body></html>`, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "no-store" } });
}
